master_dict = {
  "Alien Names": "https://www.fantasynamegenerators.com/alien-names.php",
  "Amazon Names": "https://www.fantasynamegenerators.com/amazon-names.php",
  "Anansi Names": "https://www.fantasynamegenerators.com/anansi-names.php",
  "Angel Names": "https://www.fantasynamegenerators.com/angel-names.php",
  "Animal Species Names": "https://www.fantasynamegenerators.com/animal-species-names.php",
  "Animatronic Names": "https://www.fantasynamegenerators.com/animatronic-names.php",
  "Anime Character Names": "https://www.fantasynamegenerators.com/anime-character-names.php",
  "Anthousai Names": "https://www.fantasynamegenerators.com/anthousai-names.php",
  "Anz\u00fb Names": "https://www.fantasynamegenerators.com/anzu-names.php",
  "Apocalypse/Mutant Names": "https://www.fantasynamegenerators.com/apocalypse-mutant-names.php",
  "Artificial Intelligence Names": "https://www.fantasynamegenerators.com/artificial-intelligence-names.php",
  "Bandit Names": "https://www.fantasynamegenerators.com/bandit-names.php",
  "Banshee Names": "https://www.fantasynamegenerators.com/banshee-names.php",
  "Barbarian Names": "https://www.fantasynamegenerators.com/barbarian-names.php",
  "Basilisk Names": "https://www.fantasynamegenerators.com/basilisk-names.php",
  "Birdfolk Names": "https://www.fantasynamegenerators.com/birdfolk-names.php",
  "Bluecap Names": "https://www.fantasynamegenerators.com/bluecap-names.php",
  "Bounty Hunter Names": "https://www.fantasynamegenerators.com/bounty-hunter-names.php",
  "Brownie Names": "https://www.fantasynamegenerators.com/brownie-names.php",
  "Caladrius Names": "https://www.fantasynamegenerators.com/caladrius-names.php",
  "Cat-people/Nekojin Names": "https://www.fantasynamegenerators.com/cat-people-nekojin-names.php",
  "Cavemen Names": "https://www.fantasynamegenerators.com/cavemen-names.php",
  "Centaur Names": "https://www.fantasynamegenerators.com/centaur-names.php",
  "Cerberus Names": "https://www.fantasynamegenerators.com/cerberus-names.php",
  "Christmas Elf Names": "https://www.fantasynamegenerators.com/christmas-elf-names.php",
  "Cockatrice Names": "https://www.fantasynamegenerators.com/cockatrice-names.php",
  "Code Names": "https://www.fantasynamegenerators.com/code-names.php",
  "Cowboy/girl Names": "https://www.fantasynamegenerators.com/cowboy-names.php",
  "Cyberpunk (Nick)Names": "https://www.fantasynamegenerators.com/cyberpunk-names.php",
  "Dark Elf Names": "https://www.fantasynamegenerators.com/dark-elf-names.php",
  "Death Names": "https://www.fantasynamegenerators.com/death-names.php",
  "Death Worm Names": "https://www.fantasynamegenerators.com/death-worm-names.php",
  "Demon Names": "https://www.fantasynamegenerators.com/demon-names.php",
  "Detective Names": "https://www.fantasynamegenerators.com/detective-names.php",
  "Dracaenae Names": "https://www.fantasynamegenerators.com/dracaenae-names.php",
  "Dragon Names": "https://www.fantasynamegenerators.com/dragon-names.php",
  "Dragon Names (Chinese)": "https://www.fantasynamegenerators.com/chinese-dragon-names.php",
  "Dragon Names (Japanese)": "https://www.fantasynamegenerators.com/japanese-dragon-names.php",
  "Dragonkin Names": "https://www.fantasynamegenerators.com/dragonkin-names.php",
  "Druid Groves": "https://www.fantasynamegenerators.com/druid-grove-names.php",
  "Dryad Names": "https://www.fantasynamegenerators.com/dryad-names.php",
  "Dwarf Names": "https://www.fantasynamegenerators.com/dwarf-names.php",
  "Elemental Names": "https://www.fantasynamegenerators.com/elemental-names.php",
  "Elf Names": "https://www.fantasynamegenerators.com/elf-names.php",
  "Ent/Tree creature Names": "https://www.fantasynamegenerators.com/ent-names.php",
  "Evil Names": "https://www.fantasynamegenerators.com/evil-names.php",
  "Faery Court Names": "https://www.fantasynamegenerators.com/faery-court-names.php",
  "Fairy Names": "https://www.fantasynamegenerators.com/fairy-names.php",
  "Fantasy Animal Names": "https://www.fantasynamegenerators.com/fantasy-animal-names.php",
  "Fantasy Creature Names": "https://www.fantasynamegenerators.com/creature-names.php",
  "Fantasy Race Names": "https://www.fantasynamegenerators.com/fantasy-race-names.php",
  "Fantasy Surnames": "https://www.fantasynamegenerators.com/fantasy-surnames.php",
  "Fursona Names": "https://www.fantasynamegenerators.com/fursona-names.php",
  "Futuristic Names": "https://www.fantasynamegenerators.com/futuristic-names.php",
  "Gargoyle Names": "https://www.fantasynamegenerators.com/gargoyle-names.php",
  "Genie Names": "https://www.fantasynamegenerators.com/genie-names.php",
  "Ghost Classifications": "https://www.fantasynamegenerators.com/ghost-classifications.php",
  "Ghost/Spirit Names": "https://www.fantasynamegenerators.com/ghost-names.php",
  "Ghoul Names": "https://www.fantasynamegenerators.com/ghoul-names.php",
  "Giant Names": "https://www.fantasynamegenerators.com/giant-names.php",
  "Gnoll Names": "https://www.fantasynamegenerators.com/gnoll-names.php",
  "Gnome Names": "https://www.fantasynamegenerators.com/gnome-names.php",
  "Goblin Names": "https://www.fantasynamegenerators.com/goblin-names.php",
  "God & Goddess Names": "https://www.fantasynamegenerators.com/god-names.php",
  "Golem Names": "https://www.fantasynamegenerators.com/golem-names.php",
  "Gorgon Names": "https://www.fantasynamegenerators.com/gorgon-names.php",
  "Graeae Names": "https://www.fantasynamegenerators.com/graeae-names.php",
  "Griffin Names": "https://www.fantasynamegenerators.com/griffin-names.php",
  "Grootslang Names": "https://www.fantasynamegenerators.com/grootslang-names.php",
  "Guardian Names": "https://www.fantasynamegenerators.com/guardian-names.php",
  "Half-Elf Names": "https://www.fantasynamegenerators.com/half-elf-names.php",
  "Half-Orc Names": "https://www.fantasynamegenerators.com/half-orc-names.php",
  "Harpy Names": "https://www.fantasynamegenerators.com/harpy-names.php",
  "Hellhound Names": "https://www.fantasynamegenerators.com/hellhound-names.php",
  "Hobbit Names": "https://www.fantasynamegenerators.com/hobbit-names.php",
  "(Heroic) Horse Names": "https://www.fantasynamegenerators.com/horse-names.php",
  "Hydra Names": "https://www.fantasynamegenerators.com/hydra-names.php",
  "Ifrit Names": "https://www.fantasynamegenerators.com/ifrit-names.php",
  "Imp Names": "https://www.fantasynamegenerators.com/imp-names.php",
  "Jackalopes & Wolpertingers": "https://www.fantasynamegenerators.com/jackalope-wolpertinger-names.php",
  "Jotunn Names": "https://www.fantasynamegenerators.com/jotunn-names.php",
  "J\u00f6rmungandr Names": "https://www.fantasynamegenerators.com/j%C3%B6rmungandr-names.php",
  "Kaiju Names": "https://www.fantasynamegenerators.com/kaiju-names.php",
  "Killer Names": "https://www.fantasynamegenerators.com/killer-names.php",
  "Kitsune Names": "https://www.fantasynamegenerators.com/kitsune-names.php",
  "Knight Names": "https://www.fantasynamegenerators.com/knight-names.php",
  "Kobold Names": "https://www.fantasynamegenerators.com/kobold-names.php",
  "Lamia Names": "https://www.fantasynamegenerators.com/lamia-names.php",
  "Legendary Creature Names": "https://www.fantasynamegenerators.com/legendary-creature-names.php",
  "Lich Names": "https://www.fantasynamegenerators.com/lich-names.php",
  "Lizardfolk Names": "https://www.fantasynamegenerators.com/lizardfolk-names.php",
  "Mad Scientist Names": "https://www.fantasynamegenerators.com/mad-scientist-names.php",
  "Magic User Names": "https://www.fantasynamegenerators.com/magic-user-names.php",
  "Manananggal Names": "https://www.fantasynamegenerators.com/manananggal-names.php",
  "Manticore Names": "https://www.fantasynamegenerators.com/manticore-names.php",
  "Mecha Names": "https://www.fantasynamegenerators.com/mecha-names.php",
  "Medieval Names": "https://www.fantasynamegenerators.com/medieval-names.php",
  "Mermaid/Merman Names": "https://www.fantasynamegenerators.com/mermaid-names.php",
  "Minotaur Names": "https://www.fantasynamegenerators.com/minotaur-names.php",
  "Mirrored Twin Names": "https://www.fantasynamegenerators.com/mirrored-twin-names.php",
  "Monster Names": "https://www.fantasynamegenerators.com/monster-names.php",
  "Moon Rabbit Names": "https://www.fantasynamegenerators.com/moon-rabbit-names.php",
  "Morgen Names": "https://www.fantasynamegenerators.com/morgen-names.php",
  "Mutant Species Names": "https://www.fantasynamegenerators.com/mutant-species-names.php",
  "Naga Names": "https://www.fantasynamegenerators.com/naga-names.php",
  "Necromancer Names": "https://www.fantasynamegenerators.com/necromancer-names.php",
  "Nephilim Names": "https://www.fantasynamegenerators.com/nephilim-names.php",
  "Ninja & Assassin Names": "https://www.fantasynamegenerators.com/ninja-names.php",
  "Non-Magic User Names": "https://www.fantasynamegenerators.com/non-magic-user-names.php",
  "Norse Raven Names": "https://www.fantasynamegenerators.com/norse-raven-names.php",
  "Nymph Names": "https://www.fantasynamegenerators.com/nymph-names.php",
  "Ogre Names": "https://www.fantasynamegenerators.com/ogre-names.php",
  "Orc Names": "https://www.fantasynamegenerators.com/orc-names.php",
  "Pegasus Names": "https://www.fantasynamegenerators.com/pegasus-names.php",
  "Aliens": "https://www.fantasynamegenerators.com/pet-alien-names.php",
  "Amphibians": "https://www.fantasynamegenerators.com/pet-amphibian-names.php",
  "Bats": "https://www.fantasynamegenerators.com/pet-bat-names.php",
  "Bears": "https://www.fantasynamegenerators.com/pet-bear-names.php",
  "Birds": "https://www.fantasynamegenerators.com/pet-bird-names.php",
  "Birds of Prey": "https://www.fantasynamegenerators.com/pet-bird-of-prey-names.php",
  "Cats & Felines": "https://www.fantasynamegenerators.com/pet-cat-names.php",
  "Cows": "https://www.fantasynamegenerators.com/pet-cow-names.php",
  "Crabs": "https://www.fantasynamegenerators.com/pet-crab-names.php",
  "Deer": "https://www.fantasynamegenerators.com/pet-deer-names.php",
  "Dogs & Canines": "https://www.fantasynamegenerators.com/pet-dog-names.php",
  "Elephants": "https://www.fantasynamegenerators.com/pet-elephant-names.php",
  "Fish": "https://www.fantasynamegenerators.com/pet-fish-names.php",
  "Horses": "https://www.fantasynamegenerators.com/pet-horse-names.php",
  "Insects": "https://www.fantasynamegenerators.com/pet-insect-names.php",
  "Large Cats": "https://www.fantasynamegenerators.com/pet-lion-names.php",
  "Marine Mammals": "https://www.fantasynamegenerators.com/pet-marine-mammal-names.php",
  "Mice & Rats": "https://www.fantasynamegenerators.com/pet-mouse-names.php",
  "Monkeys": "https://www.fantasynamegenerators.com/pet-monkey-names.php",
  "Owls": "https://www.fantasynamegenerators.com/pet-owl-names.php",
  "Parrots": "https://www.fantasynamegenerators.com/pet-parrot-names.php",
  "Pigs": "https://www.fantasynamegenerators.com/pet-pig-names.php",
  "Rabbits": "https://www.fantasynamegenerators.com/pet-rabbit-names.php",
  "Reptiles": "https://www.fantasynamegenerators.com/pet-reptile-names.php",
  "Rodents": "https://www.fantasynamegenerators.com/pet-rodent-names.php",
  "Sheep": "https://www.fantasynamegenerators.com/pet-sheep-names.php",
  "Turtles": "https://www.fantasynamegenerators.com/pet-turtle-names.php",
  "Wolves": "https://www.fantasynamegenerators.com/pet-wolf-names.php",
  "Phoenix Names": "https://www.fantasynamegenerators.com/phoenix-names.php",
  "Pirate Names": "https://www.fantasynamegenerators.com/pirate-names.php",
  "Pixie Names": "https://www.fantasynamegenerators.com/pixie-names.php",
  "Plague Doctors": "https://www.fantasynamegenerators.com/plague-doctor-names.php",
  "Prophet Names": "https://www.fantasynamegenerators.com/prophet-names.php",
  "Puppet Names": "https://www.fantasynamegenerators.com/puppet-names.php",
  "Qilin Names": "https://www.fantasynamegenerators.com/qilin-names.php",
  "Quetzalcoatl Names": "https://www.fantasynamegenerators.com/quetzalcoatl-names.php",
  "Rakshasa Names": "https://www.fantasynamegenerators.com/rakshasa-names.php",
  "Robot Names": "https://www.fantasynamegenerators.com/robot-names.php",
  "Roc Names": "https://www.fantasynamegenerators.com/roc-names.php",
  "Satyr & Faun Names": "https://www.fantasynamegenerators.com/satyr-faun-names.php",
  "Sea Creature Names": "https://www.fantasynamegenerators.com/sea-creature-names.php",
  "Selkie Names": "https://www.fantasynamegenerators.com/selkie-names.php",
  "Servant Names": "https://www.fantasynamegenerators.com/servant-names.php",
  "Shapeshifter Names": "https://www.fantasynamegenerators.com/shapeshifter-names.php",
  "Siren Names": "https://www.fantasynamegenerators.com/siren-names.php",
  "Slave Names": "https://www.fantasynamegenerators.com/slave-names.php",
  "Species Names": "https://www.fantasynamegenerators.com/species-names.php",
  "Sphinx Names": "https://www.fantasynamegenerators.com/sphinx-names.php",
  "Spiderfolk Names": "https://www.fantasynamegenerators.com/spiderfolk-names.php",
  "Steampunk Names": "https://www.fantasynamegenerators.com/steampunk-names.php",
  "Succubus Names": "https://www.fantasynamegenerators.com/succubus-names.php",
  "Superhero Names": "https://www.fantasynamegenerators.com/hero-names.php",
  "Superhero Team Names": "https://www.fantasynamegenerators.com/superhero-team-names.php",
  "Super Villain Names": "https://www.fantasynamegenerators.com/villain-names.php",
  "Sylph Names": "https://www.fantasynamegenerators.com/sylph-names.php",
  "Tanuki/Bake-danuki": "https://www.fantasynamegenerators.com/tanuki-names.php",
  "Titan Names": "https://www.fantasynamegenerators.com/titan-names.php",
  "Tokoloshe Names": "https://www.fantasynamegenerators.com/tokoloshe-names.php",
  "Troll Names": "https://www.fantasynamegenerators.com/troll-names.php",
  "Unicorn Names": "https://www.fantasynamegenerators.com/unicorn-names.php",
  "Valkyrie Names": "https://www.fantasynamegenerators.com/valkyrie-names.php",
  "Vampire Names": "https://www.fantasynamegenerators.com/vampire-names.php",
  "Vampire Clan Names": "https://www.fantasynamegenerators.com/vampire-clan-names.php",
  "Warrior Nicknames": "https://www.fantasynamegenerators.com/warrior-nicknames.php",
  "Werewolf Names": "https://www.fantasynamegenerators.com/werewolf-names.php",
  "Werewolf Pack Names": "https://www.fantasynamegenerators.com/werewolf-pack-names.php",
  "Witch Names": "https://www.fantasynamegenerators.com/witch-names.php",
  "Witch Coven Names": "https://www.fantasynamegenerators.com/witch-coven-names.php",
  "Wizard Names": "https://www.fantasynamegenerators.com/wizard-names.php",
  "World Defender Names": "https://www.fantasynamegenerators.com/world-defender-names.php",
  "World Destroyer Names": "https://www.fantasynamegenerators.com/world-destroyer-names.php",
  "Character names": "https://www.fantasynamegenerators.com/wuxia-names.php",
  "Sect/Clan names": "https://www.fantasynamegenerators.com/wuxia-sect-names.php",
  "Wyvern Names": "https://www.fantasynamegenerators.com/wyvern-names.php",
  "Xana Names": "https://www.fantasynamegenerators.com/xana-names.php",
  "Xianxia Titles": "https://www.fantasynamegenerators.com/xianxia-character-titles.php",
  "Yeti Names": "https://www.fantasynamegenerators.com/yeti-names.php",
  "Zaratan Names": "https://www.fantasynamegenerators.com/zaratan-names.php",
  "Zombie Types": "https://www.fantasynamegenerators.com/zombie-types.php",
  "African-American Names": "https://www.fantasynamegenerators.com/african-american-names.php",
  "Afrikaans Names": "https://www.fantasynamegenerators.com/afrikaans-names.php",
  "Akan Names": "https://www.fantasynamegenerators.com/akan-names.php",
  "Algerian Names": "https://www.fantasynamegenerators.com/algerian-names.php",
  "Amazigh Names": "https://www.fantasynamegenerators.com/amazigh-names.php",
  "Arabic/Muslim Names": "https://www.fantasynamegenerators.com/muslim-names.php",
  "Basotho Names": "https://www.fantasynamegenerators.com/basotho-names.php",
  "Biblical Names": "https://www.fantasynamegenerators.com/biblical-names.php",
  "Cameroonian Names": "https://www.fantasynamegenerators.com/cameroonian-names.php",
  "Egyptian Names (Ancient)": "https://www.fantasynamegenerators.com/egyptian-names.php",
  "Egyptian Names (Modern)": "https://www.fantasynamegenerators.com/modern-egyptian-names.php",
  "Eritrean Names": "https://www.fantasynamegenerators.com/eritrean-names.php",
  "Ethiopian Names": "https://www.fantasynamegenerators.com/ethiopian-names.php",
  "Hausa Names": "https://www.fantasynamegenerators.com/hausa-names.php",
  "Igbo Names": "https://www.fantasynamegenerators.com/igbo-names.php",
  "Kikuyu Names": "https://www.fantasynamegenerators.com/kikuyu-names.php",
  "Luo Names": "https://www.fantasynamegenerators.com/luo-names.php",
  "Malagasy Names": "https://www.fantasynamegenerators.com/malagasy-names.php",
  "Malian Names": "https://www.fantasynamegenerators.com/malian-names.php",
  "Mandinka Names": "https://www.fantasynamegenerators.com/mandinka-names.php",
  "Moorish Names": "https://www.fantasynamegenerators.com/moorish-names.php",
  "Moroccan Names": "https://www.fantasynamegenerators.com/moroccan-names.php",
  "Ndebele Names": "https://www.fantasynamegenerators.com/ndebele-names.php",
  "Oromo Names": "https://www.fantasynamegenerators.com/oromo-names.php",
  "Royalty Names": "https://www.fantasynamegenerators.com/royalty-names.php",
  "Shona Names": "https://www.fantasynamegenerators.com/shona-names.php",
  "Somali Names": "https://www.fantasynamegenerators.com/somali-names.php",
  "Swahili Names": "https://www.fantasynamegenerators.com/swahili-names.php",
  "Tshiluba Names": "https://www.fantasynamegenerators.com/tshiluba-names.php",
  "Tswana Names": "https://www.fantasynamegenerators.com/tswana-names.php",
  "Tuareg Names": "https://www.fantasynamegenerators.com/tuareg-names.php",
  "Xhosa Names": "https://www.fantasynamegenerators.com/xhosa-names.php",
  "Xitsonga Names": "https://www.fantasynamegenerators.com/xitsonga-names.php",
  "Yoruba Names": "https://www.fantasynamegenerators.com/yoruba-names.php",
  "Zambian Names": "https://www.fantasynamegenerators.com/zambian-names.php",
  "Zulu Names": "https://www.fantasynamegenerators.com/zulu-names.php",
  "Amish Names": "https://www.fantasynamegenerators.com/amish-names.php",
  "Argentinian Names": "https://www.fantasynamegenerators.com/argentinian-names.php",
  "Aztec (Nahuatl) Names": "https://www.fantasynamegenerators.com/aztec-names.php",
  "Brazilian Names": "https://www.fantasynamegenerators.com/brazilian-names.php",
  "Cajun Names": "https://www.fantasynamegenerators.com/cajun-names.php",
  "Canadian Names": "https://www.fantasynamegenerators.com/canadian-names.php",
  "Colonial American Names": "https://www.fantasynamegenerators.com/colonial-american-names.php",
  "Cosmic Names": "https://www.fantasynamegenerators.com/cosmic-names.php",
  "English (American)": "https://www.fantasynamegenerators.com/english-names.php",
  "Haitian Names": "https://www.fantasynamegenerators.com/haitian-names.php",
  "Hawaiian Names": "https://www.fantasynamegenerators.com/hawaiian-names.php",
  "Hillbilly Names": "https://www.fantasynamegenerators.com/hillbilly-names.php",
  "Hippie Names": "https://www.fantasynamegenerators.com/hippie-names.php",
  "Hispanic Names": "https://www.fantasynamegenerators.com/hispanic-names.php",
  "Inuit Names": "https://www.fantasynamegenerators.com/inuit-names.php",
  "Jamaican Names": "https://www.fantasynamegenerators.com/jamaican-names.php",
  "Maya Names": "https://www.fantasynamegenerators.com/mayan-names.php",
  "Mormon/Latter-Day Saints": "https://www.fantasynamegenerators.com/mormon-latter-day-saints-names.php",
  "Native American Names": "https://www.fantasynamegenerators.com/native-american-names.php",
  "Nature Names": "https://www.fantasynamegenerators.com/nature-names.php",
  "Puerto Rican Names": "https://www.fantasynamegenerators.com/puerto-rican-names.php",
  "Quebecois Names": "https://www.fantasynamegenerators.com/quebecois-names.php",
  "Quechua Names": "https://www.fantasynamegenerators.com/quechua-names.php",
  "Stage Names": "https://www.fantasynamegenerators.com/stage-names.php",
  "Tahitian Names": "https://www.fantasynamegenerators.com/tahitian-names.php",
  "Trinidad & Tobago Names": "https://www.fantasynamegenerators.com/trinidad-tobago-names.php",
  "Twin Names": "https://www.fantasynamegenerators.com/twin-names.php",
  "Armenian Names": "https://www.fantasynamegenerators.com/armenian-names.php",
  "Assamese Names": "https://www.fantasynamegenerators.com/assamese-names.php",
  "Bengali Names": "https://www.fantasynamegenerators.com/bengali-names.php",
  "Burmese/Myanmar Names": "https://www.fantasynamegenerators.com/burmese-myanmar-names.php",
  "Chinese Names": "https://www.fantasynamegenerators.com/chinese-names.php",
  "Dari Names": "https://www.fantasynamegenerators.com/dari-names.php",
  "Filipino Names": "https://www.fantasynamegenerators.com/filipino-names.php",
  "Gujarati Names": "https://www.fantasynamegenerators.com/gujarati-names.php",
  "Hindi Names": "https://www.fantasynamegenerators.com/hindi-names.php",
  "Hittite Names": "https://www.fantasynamegenerators.com/hittite-names.php",
  "Hmong Names": "https://www.fantasynamegenerators.com/hmong-names.php",
  "Indonesian Names": "https://www.fantasynamegenerators.com/indonesian-names.php",
  "Japanese Names": "https://www.fantasynamegenerators.com/japanese-names.php",
  "Japanese (Edo) Names": "https://www.fantasynamegenerators.com/edo-japanese-names.php",
  "Kannada Names": "https://www.fantasynamegenerators.com/kannada-names.php",
  "Kazakh Names": "https://www.fantasynamegenerators.com/kazakh-names.php",
  "Keralite Names": "https://www.fantasynamegenerators.com/keralite-names.php",
  "Khmer Names": "https://www.fantasynamegenerators.com/khmer-names.php",
  "Korean Names": "https://www.fantasynamegenerators.com/korean-names.php",
  "Kurdish Names": "https://www.fantasynamegenerators.com/kurdish-names.php",
  "Kyrgyz Names": "https://www.fantasynamegenerators.com/kyrgyz-names.php",
  "Laotian Names": "https://www.fantasynamegenerators.com/laotian-names.php",
  "Malaysian Names": "https://www.fantasynamegenerators.com/malaysian-names.php",
  "Marathi Names": "https://www.fantasynamegenerators.com/marathi-names.php",
  "Marwari Names": "https://www.fantasynamegenerators.com/marwari-names.php",
  "Mongolian (Medieval)": "https://www.fantasynamegenerators.com/medieval-mongolian-names.php",
  "Mongolian Names": "https://www.fantasynamegenerators.com/mongolian-names.php",
  "Nepalese Names": "https://www.fantasynamegenerators.com/nepalese-names.php",
  "Oriya Names": "https://www.fantasynamegenerators.com/oriya-names.php",
  "Pakistani Names": "https://www.fantasynamegenerators.com/pakistani-names.php",
  "Pashtun Names": "https://www.fantasynamegenerators.com/pashtun-names.php",
  "Persian/Iranian Names": "https://www.fantasynamegenerators.com/persian-names.php",
  "Punjabi Names": "https://www.fantasynamegenerators.com/punjabi-names.php",
  "Russian Names": "https://www.fantasynamegenerators.com/russian-names.php",
  "Sanskrit Names": "https://www.fantasynamegenerators.com/sanskrit-names.php",
  "Sikh Names": "https://www.fantasynamegenerators.com/sikh-names.php",
  "Sindhi Names": "https://www.fantasynamegenerators.com/sindhi-names.php",
  "Sinhalese Names": "https://www.fantasynamegenerators.com/sinhalese-names.php",
  "Sundanese Names": "https://www.fantasynamegenerators.com/sundanese-names.php",
  "Tajik Names": "https://www.fantasynamegenerators.com/tajik-names.php",
  "Tamil Names": "https://www.fantasynamegenerators.com/tamil-names.php",
  "Tatar Names": "https://www.fantasynamegenerators.com/tatar-names.php",
  "Telugu Names": "https://www.fantasynamegenerators.com/telugu-names.php",
  "Thai Names": "https://www.fantasynamegenerators.com/thai-names.php",
  "Tibetan Names": "https://www.fantasynamegenerators.com/tibetan-names.php",
  "Turkish Names": "https://www.fantasynamegenerators.com/turkish-names.php",
  "Urdu Names": "https://www.fantasynamegenerators.com/urdu-names.php",
  "Uyghur Names": "https://www.fantasynamegenerators.com/uyghur-names.php",
  "Uzbek Names": "https://www.fantasynamegenerators.com/uzbek-names.php",
  "Vietnamese Names": "https://www.fantasynamegenerators.com/vietnamese-names.php",
  "Yakut Names": "https://www.fantasynamegenerators.com/yakut-names.php",
  "Zoroastrian Names": "https://www.fantasynamegenerators.com/zoroastrian-names.php",
  "20th Cent. English": "https://www.fantasynamegenerators.com/20th-century-english-names.php",
  "Albanian Names": "https://www.fantasynamegenerators.com/albanian-names.php",
  "Ancient Greek Names": "https://www.fantasynamegenerators.com/ancient-greek-names.php",
  "Anglo-Saxon Names": "https://www.fantasynamegenerators.com/anglo-saxon-names.php",
  "Aragonese Names": "https://www.fantasynamegenerators.com/aragonese-names.php",
  "Asturian Names": "https://www.fantasynamegenerators.com/asturian-names.php",
  "Austrian Names": "https://www.fantasynamegenerators.com/austrian-names.php",
  "Azerbaijani Names": "https://www.fantasynamegenerators.com/azerbaijani-names.php",
  "Bashkir Names": "https://www.fantasynamegenerators.com/bashkir-names.php",
  "Basque Names": "https://www.fantasynamegenerators.com/basque-names.php",
  "Belarusian Names": "https://www.fantasynamegenerators.com/belarusian-names.php",
  "Belgian Names": "https://www.fantasynamegenerators.com/belgian-names.php",
  "Bosniak Names": "https://www.fantasynamegenerators.com/bosniak-names.php",
  "Bulgarian Names": "https://www.fantasynamegenerators.com/bulgarian-names.php",
  "Byzantine Names": "https://www.fantasynamegenerators.com/byzantine-names.php",
  "Catalan Names": "https://www.fantasynamegenerators.com/catalan-names.php",
  "Celtic (Breton) Names": "https://www.fantasynamegenerators.com/celtic-breton-names.php",
  "Celtic (Gaul) Names": "https://www.fantasynamegenerators.com/celtic-gaul-names.php",
  "Celtic (Irish) Names": "https://www.fantasynamegenerators.com/irish-names.php",
  "Celtic (Manx) Names": "https://www.fantasynamegenerators.com/manx-names.php",
  "Celtic (Scottish) Names": "https://www.fantasynamegenerators.com/celtic-names.php",
  "Celtic (Welsh) Names": "https://www.fantasynamegenerators.com/celtic-welsh-names.php",
  "Chechen Names": "https://www.fantasynamegenerators.com/chechen-names.php",
  "Circassian Names": "https://www.fantasynamegenerators.com/circassian-names.php",
  "Cornish Names": "https://www.fantasynamegenerators.com/cornish-names.php",
  "Croatian Names": "https://www.fantasynamegenerators.com/croatian-names.php",
  "Cypriot Names": "https://www.fantasynamegenerators.com/cypriot-names.php",
  "Czech Names": "https://www.fantasynamegenerators.com/czech-names.php",
  "Danish Names": "https://www.fantasynamegenerators.com/danish-names.php",
  "Dutch Names": "https://www.fantasynamegenerators.com/dutch-names.php",
  "Edwardian Names": "https://www.fantasynamegenerators.com/edwardian-names.php",
  "Elizabethan Names": "https://www.fantasynamegenerators.com/elizabethan-names.php",
  "English (British)": "https://www.fantasynamegenerators.com/british-english-names.php",
  "Enochian Names": "https://www.fantasynamegenerators.com/enochian-names.php",
  "Estonian Names": "https://www.fantasynamegenerators.com/estonian-names.php",
  "Etruscan Names": "https://www.fantasynamegenerators.com/etruscan-names.php",
  "Faroese Names": "https://www.fantasynamegenerators.com/faroese-names.php",
  "Finnish Names": "https://www.fantasynamegenerators.com/finnish-names.php",
  "Frankish Names": "https://www.fantasynamegenerators.com/frankish-names.php",
  "French Names": "https://www.fantasynamegenerators.com/french-names.php",
  "Frisian Names": "https://www.fantasynamegenerators.com/frisian-names.php",
  "Galician Names": "https://www.fantasynamegenerators.com/galician-names.php",
  "Georgian Names": "https://www.fantasynamegenerators.com/georgian-names.php",
  "German Names": "https://www.fantasynamegenerators.com/german-names.php",
  "Gothic Names": "https://www.fantasynamegenerators.com/gothic-names.php",
  "Greek Names": "https://www.fantasynamegenerators.com/greek-names.php",
  "Hellenic Names": "https://www.fantasynamegenerators.com/hellenic-names.php",
  "Hungarian Names": "https://www.fantasynamegenerators.com/hungarian-names.php",
  "Icelandic Names": "https://www.fantasynamegenerators.com/icelandic-names.php",
  "Irish Names": "https://www.fantasynamegenerators.com/modern-irish-names.php",
  "Italian Names": "https://www.fantasynamegenerators.com/italian-names.php",
  "Latin Names": "https://www.fantasynamegenerators.com/latin-names.php",
  "Latvian Names": "https://www.fantasynamegenerators.com/latvian-names.php",
  "Lithuanian Names": "https://www.fantasynamegenerators.com/lithuanian-names.php",
  "Luxembourgish Names": "https://www.fantasynamegenerators.com/luxembourgish-names.php",
  "Macedonian Names": "https://www.fantasynamegenerators.com/macedonian-names.php",
  "Maltese Names": "https://www.fantasynamegenerators.com/maltese-names.php",
  "Moldovan Names": "https://www.fantasynamegenerators.com/moldovan-names.php",
  "Montenegrin Names": "https://www.fantasynamegenerators.com/montenegrin-names.php",
  "Norman Names": "https://www.fantasynamegenerators.com/norman-names.php",
  "Norwegian Names": "https://www.fantasynamegenerators.com/norwegian-names.php",
  "Old High German Names": "https://www.fantasynamegenerators.com/old-high-german-names.php",
  "Papal Names": "https://www.fantasynamegenerators.com/papal-names.php",
  "Pictish Names": "https://www.fantasynamegenerators.com/pictish-names.php",
  "Polish Names": "https://www.fantasynamegenerators.com/polish-names.php",
  "Portuguese Names": "https://www.fantasynamegenerators.com/portuguese-names.php",
  "Puritan Names": "https://www.fantasynamegenerators.com/puritan-names.php",
  "Dutch": "https://www.fantasynamegenerators.com/dutch-renaissance-names.php",
  "English": "https://www.fantasynamegenerators.com/english-renaissance-names.php",
  "French": "https://www.fantasynamegenerators.com/french-renaissance-names.php",
  "German": "https://www.fantasynamegenerators.com/german-renaissance-names.php",
  "Italian": "https://www.fantasynamegenerators.com/italian-renaissance-names.php",
  "Portuguese": "https://www.fantasynamegenerators.com/portuguese-renaissance-names.php",
  "Spanish": "https://www.fantasynamegenerators.com/spanish-renaissance-names.php",
  "Roma Names": "https://www.fantasynamegenerators.com/roma-gypsy-names.php",
  "Roman Names": "https://www.fantasynamegenerators.com/roman-names.php",
  "Romanian Names": "https://www.fantasynamegenerators.com/romanian-names.php",
  "Royal/Posh (English) Names": "https://www.fantasynamegenerators.com/posh-names.php",
  "Sami Names": "https://www.fantasynamegenerators.com/sami-names.php",
  "Serbian Names": "https://www.fantasynamegenerators.com/serbian-names.php",
  "Scottish Names": "https://www.fantasynamegenerators.com/modern-scottish-names.php",
  "Shakespearean Names": "https://www.fantasynamegenerators.com/shakespearean-names.php",
  "Slavic Names": "https://www.fantasynamegenerators.com/slavic-names.php",
  "Slovak Names": "https://www.fantasynamegenerators.com/slovak-names.php",
  "Slovenian Names": "https://www.fantasynamegenerators.com/slovenian-names.php",
  "Spanish Names": "https://www.fantasynamegenerators.com/spanish-names.php",
  "Suebi Names": "https://www.fantasynamegenerators.com/suebi-names.php",
  "Swabian Names": "https://www.fantasynamegenerators.com/swabian-names.php",
  "Swedish Names": "https://www.fantasynamegenerators.com/swedish-names.php",
  "Swiss Names": "https://www.fantasynamegenerators.com/swiss-names.php",
  "Ukrainian Names": "https://www.fantasynamegenerators.com/ukrainian-names.php",
  "Victorian Names": "https://www.fantasynamegenerators.com/victorian-names.php",
  "Viking Names": "https://www.fantasynamegenerators.com/viking-names.php",
  "Welsh Names": "https://www.fantasynamegenerators.com/modern-welsh-names.php",
  "Akkadian Names": "https://www.fantasynamegenerators.com/akkadian-names.php",
  "Assyrian Names": "https://www.fantasynamegenerators.com/assyrian-names.php",
  "Babylonian Names": "https://www.fantasynamegenerators.com/babylonian-names.php",
  "Balochi Names": "https://www.fantasynamegenerators.com/balochi-names.php",
  "Hebrew (Older) Names": "https://www.fantasynamegenerators.com/hebrew-names.php",
  "Hebrew/Jewish Names": "https://www.fantasynamegenerators.com/jewish-names.php",
  "Ossetian Names": "https://www.fantasynamegenerators.com/ossetian-names.php",
  "Ottoman Names": "https://www.fantasynamegenerators.com/ottoman-names.php",
  "Palestinian Names": "https://www.fantasynamegenerators.com/palestinian-names.php",
  "Phoenician Names": "https://www.fantasynamegenerators.com/phoenician-names.php",
  "Sarmatian Names": "https://www.fantasynamegenerators.com/sarmatian-names.php",
  "Sumerian Names": "https://www.fantasynamegenerators.com/sumerian-names.php",
  "Zazaki Names": "https://www.fantasynamegenerators.com/zazaki-names.php",
  "Aboriginal Names": "https://www.fantasynamegenerators.com/aboriginal-names.php",
  "Australian Names": "https://www.fantasynamegenerators.com/australian-names.php",
  "Fijian Names": "https://www.fantasynamegenerators.com/fijian-names.php",
  "Maori Names": "https://www.fantasynamegenerators.com/maori-names.php",
  "Papuan Names": "https://www.fantasynamegenerators.com/papuan-names.php",
  "Samoan Names": "https://www.fantasynamegenerators.com/samoan-names.php",
  "Tuvaluan Names": "https://www.fantasynamegenerators.com/tuvaluan-names.php"
}

master_keys = [
  "Alien Names",
  "Amazon Names",
  "Anansi Names",
  "Angel Names",
  "Animal Species Names",
  "Animatronic Names",
  "Anime Character Names",
  "Anthousai Names",
  "Anz\u00fb Names",
  "Apocalypse/Mutant Names",
  "Artificial Intelligence Names",
  "Bandit Names",
  "Banshee Names",
  "Barbarian Names",
  "Basilisk Names",
  "Birdfolk Names",
  "Bluecap Names",
  "Bounty Hunter Names",
  "Brownie Names",
  "Caladrius Names",
  "Cat-people/Nekojin Names",
  "Cavemen Names",
  "Centaur Names",
  "Cerberus Names",
  "Christmas Elf Names",
  "Cockatrice Names",
  "Code Names",
  "Cowboy/girl Names",
  "Cyberpunk (Nick)Names",
  "Dark Elf Names",
  "Death Names",
  "Death Worm Names",
  "Demon Names",
  "Detective Names",
  "Dracaenae Names",
  "Dragon Names",
  "Dragon Names (Chinese)",
  "Dragon Names (Japanese)",
  "Dragonkin Names",
  "Druid Groves",
  "Dryad Names",
  "Dwarf Names",
  "Elemental Names",
  "Elf Names",
  "Ent/Tree creature Names",
  "Evil Names",
  "Faery Court Names",
  "Fairy Names",
  "Fantasy Animal Names",
  "Fantasy Creature Names",
  "Fantasy Race Names",
  "Fantasy Surnames",
  "Fursona Names",
  "Futuristic Names",
  "Gargoyle Names",
  "Genie Names",
  "Ghost Classifications",
  "Ghost/Spirit Names",
  "Ghoul Names",
  "Giant Names",
  "Gnoll Names",
  "Gnome Names",
  "Goblin Names",
  "God & Goddess Names",
  "Golem Names",
  "Gorgon Names",
  "Graeae Names",
  "Griffin Names",
  "Grootslang Names",
  "Guardian Names",
  "Half-Elf Names",
  "Half-Orc Names",
  "Harpy Names",
  "Hellhound Names",
  "Hobbit Names",
  "(Heroic) Horse Names",
  "Hydra Names",
  "Ifrit Names",
  "Imp Names",
  "Jackalopes & Wolpertingers",
  "Jotunn Names",
  "J\u00f6rmungandr Names",
  "Kaiju Names",
  "Killer Names",
  "Kitsune Names",
  "Knight Names",
  "Kobold Names",
  "Lamia Names",
  "Legendary Creature Names",
  "Lich Names",
  "Lizardfolk Names",
  "Mad Scientist Names",
  "Magic User Names",
  "Manananggal Names",
  "Manticore Names",
  "Mecha Names",
  "Medieval Names",
  "Mermaid/Merman Names",
  "Minotaur Names",
  "Mirrored Twin Names",
  "Monster Names",
  "Moon Rabbit Names",
  "Morgen Names",
  "Mutant Species Names",
  "Naga Names",
  "Necromancer Names",
  "Nephilim Names",
  "Ninja & Assassin Names",
  "Non-Magic User Names",
  "Norse Raven Names",
  "Nymph Names",
  "Ogre Names",
  "Orc Names",
  "Pegasus Names",
  "Aliens",
  "Amphibians",
  "Bats",
  "Bears",
  "Birds",
  "Birds of Prey",
  "Cats & Felines",
  "Cows",
  "Crabs",
  "Deer",
  "Dogs & Canines",
  "Elephants",
  "Fish",
  "Horses",
  "Insects",
  "Large Cats",
  "Marine Mammals",
  "Mice & Rats",
  "Monkeys",
  "Owls",
  "Parrots",
  "Pigs",
  "Rabbits",
  "Reptiles",
  "Rodents",
  "Sheep",
  "Turtles",
  "Wolves",
  "Phoenix Names",
  "Pirate Names",
  "Pixie Names",
  "Plague Doctors",
  "Prophet Names",
  "Puppet Names",
  "Qilin Names",
  "Quetzalcoatl Names",
  "Rakshasa Names",
  "Robot Names",
  "Roc Names",
  "Satyr & Faun Names",
  "Sea Creature Names",
  "Selkie Names",
  "Servant Names",
  "Shapeshifter Names",
  "Siren Names",
  "Slave Names",
  "Species Names",
  "Sphinx Names",
  "Spiderfolk Names",
  "Steampunk Names",
  "Succubus Names",
  "Superhero Names",
  "Superhero Team Names",
  "Super Villain Names",
  "Sylph Names",
  "Tanuki/Bake-danuki",
  "Titan Names",
  "Tokoloshe Names",
  "Troll Names",
  "Unicorn Names",
  "Valkyrie Names",
  "Vampire Names",
  "Vampire Clan Names",
  "Warrior Nicknames",
  "Werewolf Names",
  "Werewolf Pack Names",
  "Witch Names",
  "Witch Coven Names",
  "Wizard Names",
  "World Defender Names",
  "World Destroyer Names",
  "Character names",
  "Sect/Clan names",
  "Wyvern Names",
  "Xana Names",
  "Xianxia Titles",
  "Yeti Names",
  "Zaratan Names",
  "Zombie Types",
  "African-American Names",
  "Afrikaans Names",
  "Akan Names",
  "Algerian Names",
  "Amazigh Names",
  "Arabic/Muslim Names",
  "Basotho Names",
  "Biblical Names",
  "Cameroonian Names",
  "Egyptian Names (Ancient)",
  "Egyptian Names (Modern)",
  "Eritrean Names",
  "Ethiopian Names",
  "Hausa Names",
  "Igbo Names",
  "Kikuyu Names",
  "Luo Names",
  "Malagasy Names",
  "Malian Names",
  "Mandinka Names",
  "Moorish Names",
  "Moroccan Names",
  "Ndebele Names",
  "Oromo Names",
  "Royalty Names",
  "Shona Names",
  "Somali Names",
  "Swahili Names",
  "Tshiluba Names",
  "Tswana Names",
  "Tuareg Names",
  "Xhosa Names",
  "Xitsonga Names",
  "Yoruba Names",
  "Zambian Names",
  "Zulu Names",
  "Amish Names",
  "Argentinian Names",
  "Aztec (Nahuatl) Names",
  "Brazilian Names",
  "Cajun Names",
  "Canadian Names",
  "Colonial American Names",
  "Cosmic Names",
  "English (American)",
  "Haitian Names",
  "Hawaiian Names",
  "Hillbilly Names",
  "Hippie Names",
  "Hispanic Names",
  "Inuit Names",
  "Jamaican Names",
  "Maya Names",
  "Mormon/Latter-Day Saints",
  "Native American Names",
  "Nature Names",
  "Puerto Rican Names",
  "Quebecois Names",
  "Quechua Names",
  "Stage Names",
  "Tahitian Names",
  "Trinidad & Tobago Names",
  "Twin Names",
  "Armenian Names",
  "Assamese Names",
  "Bengali Names",
  "Burmese/Myanmar Names",
  "Chinese Names",
  "Dari Names",
  "Filipino Names",
  "Gujarati Names",
  "Hindi Names",
  "Hittite Names",
  "Hmong Names",
  "Indonesian Names",
  "Japanese Names",
  "Japanese (Edo) Names",
  "Kannada Names",
  "Kazakh Names",
  "Keralite Names",
  "Khmer Names",
  "Korean Names",
  "Kurdish Names",
  "Kyrgyz Names",
  "Laotian Names",
  "Malaysian Names",
  "Marathi Names",
  "Marwari Names",
  "Mongolian (Medieval)",
  "Mongolian Names",
  "Nepalese Names",
  "Oriya Names",
  "Pakistani Names",
  "Pashtun Names",
  "Persian/Iranian Names",
  "Punjabi Names",
  "Russian Names",
  "Sanskrit Names",
  "Sikh Names",
  "Sindhi Names",
  "Sinhalese Names",
  "Sundanese Names",
  "Tajik Names",
  "Tamil Names",
  "Tatar Names",
  "Telugu Names",
  "Thai Names",
  "Tibetan Names",
  "Turkish Names",
  "Urdu Names",
  "Uyghur Names",
  "Uzbek Names",
  "Vietnamese Names",
  "Yakut Names",
  "Zoroastrian Names",
  "20th Cent. English",
  "Albanian Names",
  "Ancient Greek Names",
  "Anglo-Saxon Names",
  "Aragonese Names",
  "Asturian Names",
  "Austrian Names",
  "Azerbaijani Names",
  "Bashkir Names",
  "Basque Names",
  "Belarusian Names",
  "Belgian Names",
  "Bosniak Names",
  "Bulgarian Names",
  "Byzantine Names",
  "Catalan Names",
  "Celtic (Breton) Names",
  "Celtic (Gaul) Names",
  "Celtic (Irish) Names",
  "Celtic (Manx) Names",
  "Celtic (Scottish) Names",
  "Celtic (Welsh) Names",
  "Chechen Names",
  "Circassian Names",
  "Cornish Names",
  "Croatian Names",
  "Cypriot Names",
  "Czech Names",
  "Danish Names",
  "Dutch Names",
  "Edwardian Names",
  "Elizabethan Names",
  "English (British)",
  "Enochian Names",
  "Estonian Names",
  "Etruscan Names",
  "Faroese Names",
  "Finnish Names",
  "Frankish Names",
  "French Names",
  "Frisian Names",
  "Galician Names",
  "Georgian Names",
  "German Names",
  "Gothic Names",
  "Greek Names",
  "Hellenic Names",
  "Hungarian Names",
  "Icelandic Names",
  "Irish Names",
  "Italian Names",
  "Latin Names",
  "Latvian Names",
  "Lithuanian Names",
  "Luxembourgish Names",
  "Macedonian Names",
  "Maltese Names",
  "Moldovan Names",
  "Montenegrin Names",
  "Norman Names",
  "Norwegian Names",
  "Old High German Names",
  "Papal Names",
  "Pictish Names",
  "Polish Names",
  "Portuguese Names",
  "Puritan Names",
  "Dutch",
  "English",
  "French",
  "German",
  "Italian",
  "Portuguese",
  "Spanish",
  "Roma Names",
  "Roman Names",
  "Romanian Names",
  "Royal/Posh (English) Names",
  "Sami Names",
  "Serbian Names",
  "Scottish Names",
  "Shakespearean Names",
  "Slavic Names",
  "Slovak Names",
  "Slovenian Names",
  "Spanish Names",
  "Suebi Names",
  "Swabian Names",
  "Swedish Names",
  "Swiss Names",
  "Ukrainian Names",
  "Victorian Names",
  "Viking Names",
  "Welsh Names",
  "Akkadian Names",
  "Assyrian Names",
  "Babylonian Names",
  "Balochi Names",
  "Hebrew (Older) Names",
  "Hebrew/Jewish Names",
  "Ossetian Names",
  "Ottoman Names",
  "Palestinian Names",
  "Phoenician Names",
  "Sarmatian Names",
  "Sumerian Names",
  "Zazaki Names",
  "Aboriginal Names",
  "Australian Names",
  "Fijian Names",
  "Maori Names",
  "Papuan Names",
  "Samoan Names",
  "Tuvaluan Names"
]